title: Natalie Furness # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome!
  <br><br>
  I am the GIS Specialist at Western Washington University and help
  manage the Spatial Institute. I am a biogeographer interested in 
  understanding the role of human interaction and climate change on
  physical landscapes and patterns. I use a variety of methods,
  mostly drawn from GIS, remote sensing, and ecology.
  <br><br>
  <a href="https://www.linkedin.com/in/natalie-furness/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
